Cuisine.create(name: 'American' , icon_id: 'R')
Cuisine.create(name: 'Asian' , icon_id: 'G')
Cuisine.create(name: 'Bagels' , icon_id: 'V')
Cuisine.create(name: 'Bakery' , icon_id: 'Q')
Cuisine.create(name: 'BBQ' , icon_id: '%')
Cuisine.create(name: 'British' , icon_id: '')
Cuisine.create(name: 'Burger' , icon_id: 'A')
Cuisine.create(name: 'Cafe' , icon_id: 'B')
Cuisine.create(name: 'Chinese' , icon_id: 'D')
Cuisine.create(name: 'Cuban' , icon_id: '7')
Cuisine.create(name: 'Desserts' , icon_id: 'E')
Cuisine.create(name: 'Donuts' , icon_id: 'M')
Cuisine.create(name: 'European' , icon_id: '')
Cuisine.create(name: 'Fast Food' , icon_id: 'W')
Cuisine.create(name: 'French' , icon_id: 'C')
Cuisine.create(name: 'Healthy Food' , icon_id: 'H')
Cuisine.create(name: 'Indian' , icon_id: 'J​')
Cuisine.create(name: 'Italian' , icon_id: '5')
Cuisine.create(name: 'Japanese' , icon_id: 'I')
Cuisine.create(name: 'Latin American' , icon_id: '8')
Cuisine.create(name: 'Mediterranean' , icon_id: '?')
Cuisine.create(name: 'Mexican' , icon_id: '8')
Cuisine.create(name: 'Middle Eastern' , icon_id: '?')
Cuisine.create(name: 'Moroccan' , icon_id: '@')
Cuisine.create(name: 'New American' , icon_id: 'R')
Cuisine.create(name: 'Pizza' , icon_id: 'L')
Cuisine.create(name: 'Ramen' , icon_id: '​.')
Cuisine.create(name: 'Sandwich' , icon_id: ')')
Cuisine.create(name: 'Seafood' , icon_id: 'C')
Cuisine.create(name: 'Southern' , icon_id: '0')
Cuisine.create(name: 'Steak' , icon_id: '3')
Cuisine.create(name: 'Sushi' , icon_id: 'I')
Cuisine.create(name: 'Ukrainian' , icon_id: '&')

##################################

Restaurant.create(name: "BBB", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '0', cuisine_id: Cuisine.find_by_name('Burger').id)
Restaurant.create(name: "Agadir", tenbis_enabled:false, address: "Tel Aviv", last_delivery_time: '15', cuisine_id: Cuisine.find_by_name('Burger').id)
Restaurant.create(name: "River", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '42', cuisine_id: Cuisine.find_by_name('Asian').id)
Restaurant.create(name: "Noodels", tenbis_enabled:false, address: "Tel Aviv", last_delivery_time: '67', cuisine_id: Cuisine.find_by_name('Asian').id)
Restaurant.create(name: "Breadly", tenbis_enabled:false, address: "Tel Aviv", last_delivery_time: '45', cuisine_id: Cuisine.find_by_name('Healthy Food').id)
Restaurant.create(name: "Salads and Veg", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '77', cuisine_id: Cuisine.find_by_name('Healthy Food').id)
Restaurant.create(name: "Italiano", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '87', cuisine_id: Cuisine.find_by_name('Italian').id)
Restaurant.create(name: "Little Italy", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '10', cuisine_id: Cuisine.find_by_name('Italian').id)
Restaurant.create(name: "Mexico is here", tenbis_enabled:false, address: "Tel Aviv", last_delivery_time: '33', cuisine_id: Cuisine.find_by_name('Mexican').id)
Restaurant.create(name: "Taco", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '102', cuisine_id: Cuisine.find_by_name('Mexican').id)

##################################

Review.create(name: "bla bla", rating: 2, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('BBB'))
Review.create(name: "bla bla", rating: 1, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('BBB'))
Review.create(name: "bla bla", rating: 3, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('BBB'))
Review.create(name: "bla bla", rating: 5, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('BBB'))
Review.create(name: "bla bla", rating: 5, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('BBB'))
Review.create(name: "bla bla", rating: 4, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Agadir'))
Review.create(name: "bla bla", rating: 5, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Agadir'))
Review.create(name: "bla bla", rating: 3, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Agadir'))
Review.create(name: "bla bla", rating: 4, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('River'))
Review.create(name: "bla bla", rating: 3, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('River'))
Review.create(name: "bla bla", rating: 3, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('River'))
Review.create(name: "bla bla", rating: 3, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('River'))
Review.create(name: "bla bla", rating: 5, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Noodels'))
Review.create(name: "bla bla", rating: 2, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Breadly'))
Review.create(name: "bla bla", rating: 2, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Breadly'))
Review.create(name: "bla bla", rating: 2, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Breadly'))
Review.create(name: "bla bla", rating: 5, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Salads and Veg'))
Review.create(name: "bla bla", rating: 4, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Italiano'))
Review.create(name: "bla bla", rating: 5, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Italiano'))
Review.create(name: "bla bla", rating: 1, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Mexico is here'))
Review.create(name: "bla bla", rating: 2, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Mexico is here'))
Review.create(name: "bla bla", rating: 5, comment: "eeeeee", restaurant_id: Restaurant.find_by_name('Mexico is here'))


