Cuisine.create(name: 'American')
Cuisine.create(name: 'Asian')
Cuisine.create(name: 'Bagels')
Cuisine.create(name: 'Bakery')
Cuisine.create(name: 'BBQ')
Cuisine.create(name: 'British')
Cuisine.create(name: 'Burger')
Cuisine.create(name: 'Cafe')
Cuisine.create(name: 'Chinese')
Cuisine.create(name: 'Cuban')
Cuisine.create(name: 'Desserts')
Cuisine.create(name: 'Donuts')
Cuisine.create(name: 'European')
Cuisine.create(name: 'Fast Food')
Cuisine.create(name: 'French')
Cuisine.create(name: 'Healthy Food')
Cuisine.create(name: 'Indian')
Cuisine.create(name: 'Italian')
Cuisine.create(name: 'Japanese')
Cuisine.create(name: 'Latin American')
Cuisine.create(name: 'Mediterranean')
Cuisine.create(name: 'Mexican')
Cuisine.create(name: 'Middle Eastern')
Cuisine.create(name: 'Moroccan')
Cuisine.create(name: 'New American')
Cuisine.create(name: 'Pizza')
Cuisine.create(name: 'Ramen')
Cuisine.create(name: 'Sandwich')
Cuisine.create(name: 'Seafood')
Cuisine.create(name: 'Southern')
Cuisine.create(name: 'Steak')
Cuisine.create(name: 'Sushi')
Cuisine.create(name: 'Ukrainian')

##################################

Restaurant.create(name: "BBB", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '0', cuisine_id: Cuisine.find_by_name('Burger').id)
Restaurant.create(name: "Agadir", tenbis_enabled:false, address: "Tel Aviv", last_delivery_time: '15', cuisine_id: Cuisine.find_by_name('Burger').id)
Restaurant.create(name: "River", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '42', cuisine_id: Cuisine.find_by_name('Asian').id)
Restaurant.create(name: "Noodels", tenbis_enabled:false, address: "Tel Aviv", last_delivery_time: '67', cuisine_id: Cuisine.find_by_name('Asian').id)
Restaurant.create(name: "Breadly", tenbis_enabled:false, address: "Tel Aviv", last_delivery_time: '45', cuisine_id: Cuisine.find_by_name('Healthy Food').id)
Restaurant.create(name: "Salads and Veg", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '77', cuisine_id: Cuisine.find_by_name('Healthy Food').id)
Restaurant.create(name: "Italiano", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '87', cuisine_id: Cuisine.find_by_name('Italian').id)
Restaurant.create(name: "Little Italy", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '10', cuisine_id: Cuisine.find_by_name('Italian').id)
Restaurant.create(name: "Mexico is here", tenbis_enabled:false, address: "Tel Aviv", last_delivery_time: '33', cuisine_id: Cuisine.find_by_name('Mexican').id)
Restaurant.create(name: "Taco", tenbis_enabled:true, address: "Tel Aviv", last_delivery_time: '102', cuisine_id: Cuisine.find_by_name('Mexican').id)
